trivia_questions = [
    {"question": "Golda Meir was the 3rd woman in history to serve as a countrys prime minister.", "is_true": True, "wrongCounter": 0, "fastestTime": 100},
    {"question": "Israel has more museums per capita than any other country in the world.", "is_true": True, "wrongCounter": 0, "fastestTime": 100},
    {"question": "Israel is the only liberal democracy in the middle east.", "is_true": True, "wrongCounter": 0, "fastestTime": 100},
    {"question": "glue on Israels stamps are kosher", "is_true": True, "wrongCounter": 0, "fastestTime": 100},
    {"question": "Most of the Windows NT operating system was developed by Microsoft-Israel", "is_true": True, "wrongCounter": 0, "fastestTime": 100},
    {"question": "Voice mail technology was developed in Israel.", "is_true": True, "wrongCounter": 0, "fastestTime": 100},
    {"question": "Israel is roughly half the size of Lake Michigan", "is_true": True, "wrongCounter": 0, "fastestTime": 0},
    {"question": "Israel is the only country in the world that has more trees today than it did 50 years ago.", "is_true": True, "wrongCounter": 0, "fastestTime": 100},
    {"question": "Israel is home to the largest known dog cemetery", "is_true": True, "wrongCounter": 0, "fastestTime": 100},
    {"question": "Beersheba has the largest number of chess grandmasters per capita than any other city in the world.", "is_true": True, "wrongCounter": 0, "fastestTime": 100},
    {"question": "There are 370 kibbutzim in Israel today.", "is_true": False, "wrongCounter": 0, "fastestTime": 100},
    {"question": "Israel has the eighth largest air force in the world", "is_true": False, "wrongCounter": 0, "fastestTime": 100},
    {"question": "The Israel National Trail allows people to drive through the entire country, from east to west.", "is_true": False, "wrongCounter": 0, "fastestTime": 100},
    {"question": "Engineers at Motorola Israel developed the original fax machine technology that led to todays smartphones.", "is_true": False, "wrongCounter": 0, "fastestTime": 100},
    {"question": "There are less than 100 archeological sites in Jerusalem", "is_true": False, "wrongCounter": 0, "fastestTime": 100},
    {"question": "Every year, about 100 letters are sent to Jerusalem, Israel, that are addressed to God.", "is_true": False, "wrongCounter": 0, "fastestTime": 100},
    {"question": "Israel recycles 10 precent of the waste water it creates less than any other country in the world!", "is_true": False, "wrongCounter": 0, "fastestTime": 100},
    {"question": "Science shows that babies in Israel are 10 times more likely to suffer from peanut allergies due to the popular peanut butter Israeli snack Bamba.", "is_true": False, "wrongCounter": 0, "fastestTime": 100},
    {"question": "After Tokyo and New York City, Tel Aviv has the most sushi restaurants per capita.", "is_true": True, "wrongCounter": 0, "fastestTime": 100},
    {"question": "A group in the city of Netanya broke the world record for the largest sock mosaic, using 12,000 in total.", "is_true": True, "wrongCounter": 0, "fastestTime": 100}
]
